<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.redhat.com/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.12068.1"
          urlbase="https://bugzilla.redhat.com/"
          
          maintainer="bugzilla-error-list@redhat.com"
>

    <bug>
          <bug_id>1305626</bug_id>
          
          <creation_ts>2016-02-08 13:40:00 -0500</creation_ts>
          <short_desc>python-six - Provides python2 subpackage.</short_desc>
          <delta_ts>2016-04-26 07:58:40 -0400</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>2</classification_id>
          <classification>Fedora</classification>
          <product>Fedora</product>
          <component>python-six</component>
          <version>24</version>
          <rep_platform>Unspecified</rep_platform>
          <op_sys>Unspecified</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>CURRENTRELEASE</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords></keywords>
          <priority>unspecified</priority>
          <bug_severity>unspecified</bug_severity>
          <target_milestone>---</target_milestone>
          
          <blocked>1285816</blocked>
          <everconfirmed>1</everconfirmed>
          <reporter name="William Moreno">williamjmorenor</reporter>
          <assigned_to name="Bohuslav &quot;Slavek&quot; Kabrda">bkabrda</assigned_to>
          <cc>apevec</cc>
    
    
    <cc>bkabrda</cc>
    
    
    <cc>itamar</cc>
    
    
    <cc>mrunge</cc>
    
    
    <cc>pviktori</cc>
          <qa_contact name="Fedora Extras Quality Assurance">extras-qa</qa_contact>
          
          <cf_fixed_in></cf_fixed_in>
          <cf_doc_type>Bug Fix</cf_doc_type>
          <cf_release_notes></cf_release_notes>
          <cf_story_points>---</cf_story_points>
          
          <cf_environment></cf_environment>
          <cf_last_closed>2016-04-26 07:58:40</cf_last_closed>
          <cf_type>Bug</cf_type>
          <cf_regression_status>---</cf_regression_status>
          <cf_mount_type>---</cf_mount_type>
          <cf_documentation_action>---</cf_documentation_action>
          <cf_crm></cf_crm>
          <cf_verified_branch></cf_verified_branch>
          <cf_category>---</cf_category>
          <cf_ovirt_team>---</cf_ovirt_team>
          
          <cf_cloudforms_team>---</cf_cloudforms_team>
          
          
          
          
          <target_release>---</target_release>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>9044139</commentid>
    <comment_count>0</comment_count>
    <who name="William Moreno">williamjmorenor</who>
    <bug_when>2016-02-08 13:40:40 -0500</bug_when>
    <thetext>As current python packaging guidelines please provides a python2-subpackage</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9093090</commentid>
    <comment_count>1</comment_count>
    <who name="Jan Kurik">jkurik</who>
    <bug_when>2016-02-24 09:26:49 -0500</bug_when>
    <thetext>This bug appears to have been reported against &apos;rawhide&apos; during the Fedora 24 development cycle.
Changing version to &apos;24&apos;.

More information and reason for this action is here:
https://fedoraproject.org/wiki/Fedora_Program_Management/HouseKeeping/Fedora24#Rawhide_Rebase</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9268990</commentid>
    <comment_count>2</comment_count>
    <who name="Petr Viktorin">pviktori</who>
    <bug_when>2016-04-26 07:58:40 -0400</bug_when>
    <thetext>This was fixed in version 1.9.0-3</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>