<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.redhat.com/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.12068.1"
          urlbase="https://bugzilla.redhat.com/"
          
          maintainer="bugzilla-error-list@redhat.com"
>

    <bug>
          <bug_id>1337002</bug_id>
          
          <creation_ts>2016-05-17 21:32:00 -0400</creation_ts>
          <short_desc>SELinux error when connecting to VPN</short_desc>
          <delta_ts>2016-05-28 14:34:29 -0400</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>2</classification_id>
          <classification>Fedora</classification>
          <product>Fedora</product>
          <component>selinux-policy</component>
          <version>24</version>
          <rep_platform>Unspecified</rep_platform>
          <op_sys>Unspecified</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>ERRATA</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords></keywords>
          <priority>unspecified</priority>
          <bug_severity>unspecified</bug_severity>
          <target_milestone>---</target_milestone>
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Nick Coghlan">ncoghlan</reporter>
          <assigned_to name="Lukas Vrabec">lvrabec</assigned_to>
          <cc>dominick.grift</cc>
    
    
    <cc>dwalsh</cc>
    
    
    <cc>lvrabec</cc>
    
    
    <cc>mgrepl</cc>
    
    
    <cc>plautrba</cc>
          <qa_contact name="Fedora Extras Quality Assurance">extras-qa</qa_contact>
          
          <cf_fixed_in>selinux-policy-3.13.1-188.fc24 selinux-policy-3.13.1-189.fc24</cf_fixed_in>
          <cf_doc_type>If docs needed, set a value</cf_doc_type>
          <cf_release_notes></cf_release_notes>
          <cf_story_points>---</cf_story_points>
          
          <cf_environment></cf_environment>
          <cf_last_closed>2016-05-28 14:34:29</cf_last_closed>
          <cf_type>Bug</cf_type>
          <cf_regression_status>---</cf_regression_status>
          <cf_mount_type>---</cf_mount_type>
          <cf_documentation_action>---</cf_documentation_action>
          <cf_crm></cf_crm>
          <cf_verified_branch></cf_verified_branch>
          <cf_category>---</cf_category>
          <cf_ovirt_team>---</cf_ovirt_team>
          
          <cf_cloudforms_team>---</cf_cloudforms_team>
          
          
          
          
          <target_release>---</target_release>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>9335550</commentid>
    <comment_count>0</comment_count>
    <who name="Nick Coghlan">ncoghlan</who>
    <bug_when>2016-05-17 21:32:47 -0400</bug_when>
    <thetext>Description of problem:

Running F24 Beta, I&apos;m currently getting the following error in the logs when attempting to connect to the Red Hat Brisbane VPN endpoint with SELinux in enforcing mode:

--------------------
May 18 11:09:15 thechalk NetworkManager[23516]: &lt;warn&gt;  [1463533755.9106] dnsmasq[0x56259e79a6e0]: dnsmasq update failed: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An SELinux policy prevents this sender from sending this message to this recipient, 0 matched rules; type=&quot;method_call&quot;, sender=&quot;:1.11&quot; (uid=0 pid=23516 comm=&quot;/usr/sbin/NetworkManager --no-daemon &quot;) interface=&quot;org.freedesktop.NetworkManager.dnsmasq&quot; member=&quot;SetServersEx&quot; error name=&quot;(unset)&quot; requested_reply=&quot;0&quot; destination=&quot;:1.46&quot; (uid=0 pid=24389 comm=&quot;/usr/sbin/dnsmasq --no-resolv --keep-in-foreground&quot;)
--------------------

After that, name resolution from the system doesn&apos;t work. While there was no SELinux troubleshooting alert for that particular error, there *was* an error on system startup for dhclient, complaining it didn&apos;t have permission to read /etc/machine-id.

If I run &quot;setenforce 0&quot; before connecting to the VPN, everything goes fine and name resolution continues to work (including after running &quot;setenforce 1&quot; after connecting to the VPN). 

Version-Release number of selected component (if applicable):

selinux-policy-3.13.1-185.fc24.noarch
dhcp-client-4.3.4-1.fc24.x86_64
NetworkManager-1.2.2-1.fc24.x86_64
openvpn-2.3.11-1.fc24.x86_64

How reproducible:

Always now, but it wasn&apos;t doing it when I connected to the VPN yesterday (however, all of selinux-policy, openvpn and NetworkManager were updated yesterday)

Steps to Reproduce:
1. Connect to wireless (can do DNS lookups)
2. Connect to VPN
3.

Actual results:

Can no longer do DNS lookups

Expected results:

Can do DNS lookups for both public and internal DNS

Additional info:

This system was upgraded from F23, and I&apos;d previously had to do a whole filesystem relabel after inadvertently installing the Rawhide (F25) SELinux policy.

SELinux labels on /etc/machine-id:

    $ ls -lZ /etc/machine-id
    -r--r--r--. 1 root root system_u:object_r:svirt_sandbox_file_t:s0 33 Apr 24  2015 /etc/machine-id

Running restorecon on that doesn&apos;t change the labels.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9336414</commentid>
    <comment_count>1</comment_count>
    <who name="Lukas Vrabec">lvrabec</who>
    <bug_when>2016-05-18 05:16:55 -0400</bug_when>
    <thetext>We have already fixes in selinux-policy repo.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9359988</commentid>
    <comment_count>2</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-05-26 01:02:15 -0400</bug_when>
    <thetext>selinux-policy-3.13.1-189.fc24 has been pushed to the Fedora 24 testing repository. If problems still persist, please make note of it in this bug report.
See https://fedoraproject.org/wiki/QA:Updates_Testing for
instructions on how to install test updates.
You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2016-43d1395a18</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9360013</commentid>
    <comment_count>3</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-05-26 01:03:18 -0400</bug_when>
    <thetext>selinux-policy-3.13.1-188.fc24 has been pushed to the Fedora 24 testing repository. If problems still persist, please make note of it in this bug report.
See https://fedoraproject.org/wiki/QA:Updates_Testing for
instructions on how to install test updates.
You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2016-3ccd9afa2f</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9367062</commentid>
    <comment_count>4</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-05-28 14:34:06 -0400</bug_when>
    <thetext>selinux-policy-3.13.1-189.fc24 has been pushed to the Fedora 24 stable repository. If problems still persist, please make note of it in this bug report.</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>