<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.redhat.com/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.12068.1"
          urlbase="https://bugzilla.redhat.com/"
          
          maintainer="bugzilla-error-list@redhat.com"
>

    <bug>
          <bug_id>1393569</bug_id>
          
          <creation_ts>2016-11-09 16:34:00 -0500</creation_ts>
          <short_desc>SELinux is preventing radicale from execute access on the file /usr/bin/python3.5.</short_desc>
          <delta_ts>2016-12-20 13:18:52 -0500</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>2</classification_id>
          <classification>Fedora</classification>
          <product>Fedora</product>
          <component>radicale</component>
          <version>24</version>
          <rep_platform>x86_64</rep_platform>
          <op_sys>Linux</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>ERRATA</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords></keywords>
          <priority>unspecified</priority>
          <bug_severity>medium</bug_severity>
          <target_milestone>---</target_milestone>
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Charles-Henri d&apos;Adhémar">charles-henri</reporter>
          <assigned_to name="Juan Orti">j.orti.alcaine</assigned_to>
          <cc>charles-henri</cc>
    
    
    <cc>j.orti.alcaine</cc>
    
    
    <cc>opensource</cc>
    
    
    <cc>viorel.tabara</cc>
          <qa_contact name="Fedora Extras Quality Assurance">extras-qa</qa_contact>
          
          <cf_fixed_in>radicale-1.1.1-9.fc24</cf_fixed_in>
          <cf_doc_type>If docs needed, set a value</cf_doc_type>
          <cf_release_notes></cf_release_notes>
          <cf_story_points>---</cf_story_points>
          
          <cf_environment></cf_environment>
          <cf_last_closed>2016-12-20 13:18:52</cf_last_closed>
          <cf_type>Bug</cf_type>
          <cf_regression_status>---</cf_regression_status>
          <cf_mount_type>---</cf_mount_type>
          <cf_documentation_action>---</cf_documentation_action>
          <cf_crm></cf_crm>
          <cf_verified_branch></cf_verified_branch>
          <cf_category>---</cf_category>
          <cf_ovirt_team>---</cf_ovirt_team>
          
          <cf_cloudforms_team>---</cf_cloudforms_team>
          
          
          
          
          <target_release>---</target_release>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>9877400</commentid>
    <comment_count>0</comment_count>
    <who name="Charles-Henri d&apos;Adhémar">charles-henri</who>
    <bug_when>2016-11-09 16:34:34 -0500</bug_when>
    <thetext>SELinux is preventing radicale from execute access on the file /usr/bin/python3.5.

*****  Plugin catchall (100. confidence) suggests   **************************

If you believe that radicale should be allowed execute access on the python3.5 file by default.
Then you should report this as a bug.
You can generate a local policy module to allow this access.
Do
allow this access for now by executing:
# ausearch -c &apos;radicale&apos; --raw | audit2allow -M my-radicale
# semodule -X 300 -i my-radicale.pp


Additional Information:
Source Context                system_u:system_r:radicale_t:s0
Target Context                system_u:object_r:bin_t:s0
Target Objects                /usr/bin/python3.5 [ file ]
Source                        radicale
Source Path                   radicale
Port                          &lt;Unknown&gt;
Host                          horous
Source RPM Packages           
Target RPM Packages           python3-3.5.2-3.fc24.x86_64
Policy RPM                    selinux-policy-3.13.1-191.19.fc24.noarch
Selinux Enabled               True
Policy Type                   targeted
Enforcing Mode                Enforcing
Host Name                     horous
Platform                      Linux horous 4.8.6-201.fc24.x86_64 #1 SMP Thu Nov
                              3 14:38:57 UTC 2016 x86_64 x86_64
Alert Count                   2
First Seen                    2016-11-07 18:19:36 CET
Last Seen                     2016-11-09 21:56:11 CET
Local ID                      2841e50f-9319-4435-a454-e3801ed27d21

Raw Audit Messages
type=AVC msg=audit(1478724971.764:212): avc:  denied  { execute } for  pid=5678 comm=&quot;radicale&quot; path=&quot;/usr/bin/python3.5&quot; dev=&quot;dm-0&quot; ino=8478947 scontext=system_u:system_r:radicale_t:s0 tcontext=system_u:object_r:bin_t:s0 tclass=file permissive=1


Hash: radicale,radicale_t,bin_t,file,execute</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9945130</commentid>
    <comment_count>1</comment_count>
    <who name="Viorel Tabara">viorel.tabara</who>
    <bug_when>2016-11-30 17:34:54 -0500</bug_when>
    <thetext>I was getting this on F25 with latest policy:

   [root@stuff selinux]# rpm -qa --last &quot;selinux*&quot;
   selinux-policy-devel-3.13.1-225.fc25.noarch   Wed 30 Nov 2016 03:06:51 PM MST
   selinux-policy-doc-3.13.1-225.fc25.noarch     Wed 30 Nov 2016 03:06:48 PM MST
   selinux-policy-targeted-3.13.1-225.fc25.noarch Wed 30 Nov 2016 03:06:35 PM MST
   selinux-policy-3.13.1-225.fc25.noarch         Wed 30 Nov 2016 03:06:23 PM MST
   selinux-policy-sandbox-3.13.1-224.fc25.noarch Thu 24 Nov 2016 09:45:56 AM MST
   
   Nov 30 15:17:11 stuff.can.local systemd[1]: Stopping Radicale CalDAV and CardDAV server...
   Nov 30 15:17:11 stuff.can.local systemd[1]: Stopped Radicale CalDAV and CardDAV server.
   Nov 30 15:17:11 stuff.can.local audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg=&apos;unit=radicale comm=&quot;systemd&quot; exe=&quot;/usr/lib/systemd/systemd&quot; hostname=? addr=? terminal=? res=success&apos;
   Nov 30 15:17:11 stuff.can.local systemd[1]: Starting Radicale CalDAV and CardDAV server...
   Nov 30 15:17:11 stuff.can.local audit[1396]: AVC avc:  denied  { execute } for  pid=1396 comm=&quot;radicale&quot; path=&quot;/usr/bin/python3.5&quot; dev=&quot;dm-1&quot; ino=18990 scontext=system_u:system_r:radicale_t:s0 tcontext=system_u:object_r:bin_t:s0 tclass=file permissive=1
   Nov 30 15:17:11 stuff.can.local systemd[1]: Started Radicale CalDAV and CardDAV server.
   Nov 30 15:17:11 stuff.can.local audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg=&apos;unit=radicale comm=&quot;systemd&quot; exe=&quot;/usr/lib/systemd/systemd&quot; hostname=? addr=? terminal=? res=success&apos;
   Nov 30 15:17:14 stuff.can.local dbus-daemon[1541]: [system] Activating service name=&apos;org.fedoraproject.Setroubleshootd&apos; requested by &apos;:1.37&apos; (uid=0 pid=1500 comm=&quot;/usr/sbin/sedispatch &quot; label=&quot;system_u:system_r:audisp_t:s0&quot;) (using servicehelper)
   Nov 30 15:17:15 stuff.can.local dbus-daemon[1541]: [system] Successfully activated service &apos;org.fedoraproject.Setroubleshootd&apos;
   Nov 30 15:17:16 stuff.can.local setroubleshoot[1408]: SELinux is preventing radicale from execute access on the file /usr/bin/python3.5. For complete SELinux messages. run sealert -l 77b4c560-b796-42fd-b8ef-0c7b3c2153cd
   Nov 30 15:17:16 stuff.can.local python3[1408]: SELinux is preventing radicale from execute access on the file /usr/bin/python3.5.

                                                *****  Plugin catchall (100. confidence) suggests   **************************

                                                If you believe that radicale should be allowed execute access on the python3.5 file by default.
                                                Then you should report this as a bug.
                                                You can generate a local policy module to allow this access.
                                                Do
                                                allow this access for now by executing:
                                                # ausearch -c &apos;radicale&apos; --raw | audit2allow -M my-radicale
                                                # semodule -X 300 -i my-radicale.pp


Removing the &apos;-devel&apos; packages followed by radicale service &quot;stop&quot; and &quot;start&quot; 
got rid of alerts:

   Nov 30 15:30:16 stuff.can.local systemd[1]: Stopping Radicale CalDAV and CardDAV server...
   Nov 30 15:30:16 stuff.can.local audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg=&apos;unit=radicale comm=&quot;systemd&quot; exe=&quot;/usr/lib/systemd/systemd&quot; hostname=? addr=? terminal=? res=success&apos;
   Nov 30 15:30:16 stuff.can.local systemd[1]: Stopped Radicale CalDAV and CardDAV server.
   Nov 30 15:30:27 stuff.can.local systemd[1]: Starting Radicale CalDAV and CardDAV server...
   Nov 30 15:30:28 stuff.can.local audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg=&apos;unit=radicale comm=&quot;systemd&quot; exe=&quot;/usr/lib/systemd/systemd&quot; hostname=? addr=? terminal=? res=success&apos;
   Nov 30 15:30:28 stuff.can.local systemd[1]: Started Radicale CalDAV and CardDAV server.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9945161</commentid>
    <comment_count>2</comment_count>
    <who name="Viorel Tabara">viorel.tabara</who>
    <bug_when>2016-11-30 17:50:27 -0500</bug_when>
    <thetext>Sorry, spoke too soon. Subsequent restart still trigger the alerts.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9971061</commentid>
    <comment_count>3</comment_count>
    <who name="Juan Orti">j.orti.alcaine</who>
    <bug_when>2016-12-09 05:57:22 -0500</bug_when>
    <thetext>I&apos;m not sure why we&apos;re getting those AVCs in F25, I&apos;m investigating it.

It&apos;s radicale otherwise working for you?</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9971616</commentid>
    <comment_count>4</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-12-09 08:48:27 -0500</bug_when>
    <thetext>radicale-1.1.1-9.fc25 has been submitted as an update to Fedora 25. https://bodhi.fedoraproject.org/updates/FEDORA-2016-4339113d45</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9971642</commentid>
    <comment_count>5</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-12-09 09:01:29 -0500</bug_when>
    <thetext>radicale-1.1.1-9.fc24 has been submitted as an update to Fedora 24. https://bodhi.fedoraproject.org/updates/FEDORA-2016-b644a7905e</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9972703</commentid>
    <comment_count>6</comment_count>
    <who name="Charles-Henri d&apos;Adhémar">charles-henri</who>
    <bug_when>2016-12-09 14:23:12 -0500</bug_when>
    <thetext>To be honest I have not noticed any issue with Radicale and this AVC.
All is working great.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9973334</commentid>
    <comment_count>7</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-12-09 22:58:50 -0500</bug_when>
    <thetext>radicale-1.1.1-9.fc25 has been pushed to the Fedora 25 testing repository. If problems still persist, please make note of it in this bug report.
See https://fedoraproject.org/wiki/QA:Updates_Testing for
instructions on how to install test updates.
You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2016-4339113d45</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9973367</commentid>
    <comment_count>8</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-12-09 23:29:12 -0500</bug_when>
    <thetext>radicale-1.1.1-9.fc24 has been pushed to the Fedora 24 testing repository. If problems still persist, please make note of it in this bug report.
See https://fedoraproject.org/wiki/QA:Updates_Testing for
instructions on how to install test updates.
You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2016-b644a7905e</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9974726</commentid>
    <comment_count>9</comment_count>
    <who name="Juan Orti">j.orti.alcaine</who>
    <bug_when>2016-12-11 09:23:42 -0500</bug_when>
    <thetext>If you still get the execute_no_trans in /usr/sbin/ldconfig, could you show me the file context of that file? It was wrong in my system, I don&apos;t know why.

# ls -lZ /usr/sbin/ldconfig
# restorecon -v /usr/sbin/ldconfig</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9974737</commentid>
    <comment_count>10</comment_count>
    <who name="Charles-Henri d&apos;Adhémar">charles-henri</who>
    <bug_when>2016-12-11 09:48:02 -0500</bug_when>
    <thetext>Hi Juan,

Thank you very much for your support and time here.
I have to apologies, I should have tried this first myself.

Indeed restoring the context solves the issue and I have no more AVC with radicale:

# ls -lZ /usr/sbin/ldconfig
-rwxr-xr-x. 2 root root system_u:object_r:bin_t:s0 1092864 18 août  14:21 /usr/sbin/ldconfig

#  restorecon -v /usr/sbin/ldconfig
restorecon reset /usr/sbin/ldconfig context system_u:object_r:bin_t:s0-&gt;system_u:object_r:ldconfig_exec_t:s0</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9997178</commentid>
    <comment_count>11</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-12-19 01:02:22 -0500</bug_when>
    <thetext>radicale-1.1.1-9.fc25 has been pushed to the Fedora 25 stable repository. If problems still persist, please make note of it in this bug report.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10006466</commentid>
    <comment_count>12</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-12-20 13:18:52 -0500</bug_when>
    <thetext>radicale-1.1.1-9.fc24 has been pushed to the Fedora 24 stable repository. If problems still persist, please make note of it in this bug report.</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>