<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.redhat.com/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.12068.1"
          urlbase="https://bugzilla.redhat.com/"
          
          maintainer="bugzilla-error-list@redhat.com"
>

    <bug>
          <bug_id>1401041</bug_id>
          
          <creation_ts>2016-12-02 10:48:00 -0500</creation_ts>
          <short_desc>Python traceback in dnf-plugin-spacewalk in Fedora 24</short_desc>
          <delta_ts>2016-12-04 00:25:41 -0500</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>2</classification_id>
          <classification>Fedora</classification>
          <product>Fedora</product>
          <component>dnf</component>
          <version>24</version>
          <rep_platform>Unspecified</rep_platform>
          <op_sys>Unspecified</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>ERRATA</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords></keywords>
          <priority>unspecified</priority>
          <bug_severity>unspecified</bug_severity>
          <target_milestone>---</target_milestone>
          <dependson>1395737</dependson>
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Pavel Studeník">pstudeni</reporter>
          <assigned_to>rpm-software-management</assigned_to>
          <cc>mluscon</cc>
    
    
    <cc>packaging-team-maint</cc>
    
    
    <cc>pnemade</cc>
    
    
    <cc>pstudeni</cc>
    
    
    <cc>rdrazny</cc>
    
    
    <cc>rpm-software-management</cc>
    
    
    <cc>satellite-qa-list</cc>
    
    
    <cc>tkasparek</cc>
    
    
    <cc>vmukhame</cc>
          <qa_contact name="Fedora Extras Quality Assurance">extras-qa</qa_contact>
          
          <cf_fixed_in>dnf-1.1.10-4.fc25 dnf-1.1.10-2.fc24</cf_fixed_in>
          <cf_doc_type>If docs needed, set a value</cf_doc_type>
          <cf_release_notes></cf_release_notes>
          <cf_story_points>---</cf_story_points>
          <cf_clone_of>1395737</cf_clone_of>
          <cf_environment></cf_environment>
          <cf_last_closed>2016-12-03 21:29:06</cf_last_closed>
          <cf_type>Bug</cf_type>
          <cf_regression_status>---</cf_regression_status>
          <cf_mount_type>---</cf_mount_type>
          <cf_documentation_action>---</cf_documentation_action>
          <cf_crm></cf_crm>
          <cf_verified_branch></cf_verified_branch>
          <cf_category>---</cf_category>
          <cf_ovirt_team>---</cf_ovirt_team>
          
          <cf_cloudforms_team>---</cf_cloudforms_team>
          
          
          
          
          <target_release>---</target_release>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>9951718</commentid>
    <comment_count>0</comment_count>
    <who name="Pavel Studeník">pstudeni</who>
    <bug_when>2016-12-02 10:48:41 -0500</bug_when>
    <thetext>+++ This bug was initially created as a clone of Bug #1395737 +++

Description of problem:
Doing &quot;dnf -v repolist&quot; on Fedora 24/25 ends with a traceback if -v option used.


Version-Release number of selected component (if applicable):
dnf-plugin-spacewalk-2.5.8-1.fc23
dnf-1.1.10-1.fc23

Same issue reproduced on Fedora 24 with dnf-plugin-spacewalk-2.7.1-1 from nightly-client

How reproducible:
always


Steps to Reproduce:
1. Install rhn-client-tools and rhn-setup on Fedora 23 from Spacewalk client repo.
2. Create an channel on a Spacewalk 2.5 server and create an activation key for it. Empty channel without any packages is sufficient.
3. Register Fedora client to the channel on Spacewalk server using the activation key.
4. Try running &quot;dnf -v repolist&quot;

Actual results:

Traceback (most recent call last):
  File &quot;/usr/bin/dnf&quot;, line 58, in &lt;module&gt;
    main.user_main(sys.argv[1:], exit_code=True)
  File &quot;/usr/lib/python3.4/site-packages/dnf/cli/main.py&quot;, line 174, in user_main
    errcode = main(args)
  File &quot;/usr/lib/python3.4/site-packages/dnf/cli/main.py&quot;, line 60, in main
    return _main(base, args)
  File &quot;/usr/lib/python3.4/site-packages/dnf/cli/main.py&quot;, line 112, in _main
    cli.run()
  File &quot;/usr/lib/python3.4/site-packages/dnf/cli/cli.py&quot;, line 1099, in run
    return self.command.run(self.base.extcmds)
  File &quot;/usr/lib/python3.4/site-packages/dnf/cli/commands/repolist.py&quot;, line 216, in run
    if repo.repofile:
AttributeError: &apos;SpacewalkRepo&apos; object has no attribute &apos;repofile&apos;


Expected results:
Verbose repo info is listed without any error.

Additional info:
Same issue reproduced on Fedora 24 with dnf-plugin-spacewalk-2.7.1-1 from nightly-client

--- Additional comment from Pavel Studeník on 2016-12-02 08:33:03 EST ---

Bug is not fixed in dnf-plugin-spacewalk-2.7.2-1.fc25.noarch

--- Additional comment from Pavel Studeník on 2016-12-02 10:45:58 EST ---

fix in upstream https://github.com/rpm-software-management/dnf/commit/fba7ae2890ddc725fdad3fd092278e36dd029a83</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9951811</commentid>
    <comment_count>1</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-12-02 11:13:06 -0500</bug_when>
    <thetext>dnf-1.1.10-2.fc24 has been submitted as an update to Fedora 24. https://bodhi.fedoraproject.org/updates/FEDORA-2016-08cf606646</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9951812</commentid>
    <comment_count>2</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-12-02 11:13:17 -0500</bug_when>
    <thetext>dnf-1.1.10-4.fc25 has been submitted as an update to Fedora 25. https://bodhi.fedoraproject.org/updates/FEDORA-2016-72ef1673b7</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9952961</commentid>
    <comment_count>3</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-12-02 23:37:43 -0500</bug_when>
    <thetext>dnf-1.1.10-4.fc25 has been pushed to the Fedora 25 testing repository. If problems still persist, please make note of it in this bug report.
See https://fedoraproject.org/wiki/QA:Updates_Testing for
instructions on how to install test updates.
You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2016-72ef1673b7</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9953051</commentid>
    <comment_count>4</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-12-03 00:43:23 -0500</bug_when>
    <thetext>dnf-1.1.10-2.fc24 has been pushed to the Fedora 24 testing repository. If problems still persist, please make note of it in this bug report.
See https://fedoraproject.org/wiki/QA:Updates_Testing for
instructions on how to install test updates.
You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2016-08cf606646</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9953940</commentid>
    <comment_count>5</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-12-03 21:29:06 -0500</bug_when>
    <thetext>dnf-1.1.10-4.fc25 has been pushed to the Fedora 25 stable repository. If problems still persist, please make note of it in this bug report.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9954013</commentid>
    <comment_count>6</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-12-04 00:25:41 -0500</bug_when>
    <thetext>dnf-1.1.10-2.fc24 has been pushed to the Fedora 24 stable repository. If problems still persist, please make note of it in this bug report.</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>