<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.redhat.com/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.12068.1"
          urlbase="https://bugzilla.redhat.com/"
          
          maintainer="bugzilla-error-list@redhat.com"
>

    <bug>
          <bug_id>1340507</bug_id>
          
          <creation_ts>2016-05-27 11:25:00 -0400</creation_ts>
          <short_desc>when there&apos;s scriplet error in rpm transaction, DNF raises traceback</short_desc>
          <delta_ts>2017-04-11 12:56:56 -0400</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>2</classification_id>
          <classification>Fedora</classification>
          <product>Fedora</product>
          <component>dnf</component>
          <version>25</version>
          <rep_platform>Unspecified</rep_platform>
          <op_sys>Unspecified</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>NEXTRELEASE</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords>Triaged</keywords>
          <priority>unspecified</priority>
          <bug_severity>unspecified</bug_severity>
          <target_milestone>---</target_milestone>
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Igor Gnatenko">ignatenko</reporter>
          <assigned_to>rpm-software-management</assigned_to>
          <cc>darrellpf</cc>
    
    
    <cc>jmracek</cc>
    
    
    <cc>michal.jnn</cc>
    
    
    <cc>mluscon</cc>
    
    
    <cc>packaging-team-maint</cc>
    
    
    <cc>pantinor</cc>
    
    
    <cc>vmukhame</cc>
          <qa_contact name="Fedora Extras Quality Assurance">extras-qa</qa_contact>
          
          <cf_fixed_in></cf_fixed_in>
          <cf_doc_type>If docs needed, set a value</cf_doc_type>
          <cf_release_notes></cf_release_notes>
          <cf_story_points>---</cf_story_points>
          
          <cf_environment></cf_environment>
          <cf_last_closed>2017-04-11 12:56:56</cf_last_closed>
          <cf_type>Bug</cf_type>
          <cf_regression_status>---</cf_regression_status>
          <cf_mount_type>---</cf_mount_type>
          <cf_documentation_action>---</cf_documentation_action>
          <cf_crm></cf_crm>
          <cf_verified_branch></cf_verified_branch>
          <cf_category>---</cf_category>
          <cf_ovirt_team>---</cf_ovirt_team>
          
          <cf_cloudforms_team>---</cf_cloudforms_team>
          
          
          
          
          <target_release>---</target_release>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>9365878</commentid>
    <comment_count>0</comment_count>
    <who name="Igor Gnatenko">ignatenko</who>
    <bug_when>2016-05-27 11:25:02 -0400</bug_when>
    <thetext>Failed to rename /usr/share/mime/application/x-java-archive.xml.new as /usr/share/mime/application/x-java-archive.xml: Structure needs cleaning
warning: %triggerin(shared-mime-info-1.6-1.fc24.x86_64) scriptlet failed, exit status 1
Traceback (most recent call last):
  File &quot;/usr/lib/python3.5/site-packages/dnf/yum/rpmtrans.py&quot;, line 427, in callback
    self._scriptError(bytes, total, h)
  File &quot;/usr/lib/python3.5/site-packages/dnf/yum/rpmtrans.py&quot;, line 557, in _scriptError
    pkg, _, _ = self._extract_cbkey(h)
  File &quot;/usr/lib/python3.5/site-packages/dnf/yum/rpmtrans.py&quot;, line 229, in _extract_cbkey
    return self._extract_str_cbkey(cbkey)
  File &quot;/usr/lib/python3.5/site-packages/dnf/yum/rpmtrans.py&quot;, line 237, in _extract_str_cbkey
    assert(isinstance(name, basestring))
AssertionError
FATAL ERROR: python callback ??? failed, aborting!


I was using dnf-1.1.8</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9490140</commentid>
    <comment_count>1</comment_count>
    <who name="Fedora Admin XMLRPC Client">fedora-admin-xmlrpc</who>
    <bug_when>2016-07-08 05:25:09 -0400</bug_when>
    <thetext>This package has changed ownership in the Fedora Package Database.  Reassigning to the new owner of this component.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9549879</commentid>
    <comment_count>2</comment_count>
    <who name="Jan Kurik">jkurik</who>
    <bug_when>2016-07-26 01:01:15 -0400</bug_when>
    <thetext>This bug appears to have been reported against &apos;rawhide&apos; during the Fedora 25 development cycle.
Changing version to &apos;25&apos;.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10055037</commentid>
    <comment_count>3</comment_count>
    <who name="Igor Gnatenko">ignatenko</who>
    <bug_when>2017-01-11 17:57:02 -0500</bug_when>
    <thetext>*** Bug 1411049 has been marked as a duplicate of this bug. ***</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10058636</commentid>
    <comment_count>4</comment_count>
    <who name="darrell pfeifer">darrellpf</who>
    <bug_when>2017-01-12 14:57:21 -0500</bug_when>
    <thetext>  Upgrading   : systemd-libs-232-7.fc26.x86_64                                                                            1/21 
  Upgrading   : systemd-pam-232-7.fc26.x86_64                                                                             2/21 
  Upgrading   : systemd-232-7.fc26.x86_64                                                                                 3/21 
  Upgrading   : bind99-license-9.9.9-4.P5.fc26.noarch                                                                     4/21 
  Upgrading   : bind99-libs-9.9.9-4.P5.fc26.x86_64                                                                        5/21 
  Upgrading   : systemd-udev-232-7.fc26.x86_64                                                                            6/21 
  Upgrading   : systemd-container-232-7.fc26.x86_64                                                                       7/21 
  Upgrading   : gnome-settings-daemon-3.23.3-1.fc26.x86_64                                                                8/21 
  Cleanup     : systemd-container-232-6.fc26.x86_64                                                                       9/21 
  Cleanup     : systemd-udev-232-6.fc26.x86_64                                                                           10/21 
  Cleanup     : systemd-pam-232-6.fc26.x86_64                                                                            11/21 
  Cleanup     : systemd-232-6.fc26.x86_64                                                                                12/21 
/var/tmp/rpm-tmp.6DhLlY: line 1: fg: no job control
error: %preun(systemd-udev-232-3.fc26.x86_64) scriptlet failed, exit status 1
Traceback (most recent call last):
  File &quot;/usr/lib/python3.6/site-packages/dnf/yum/rpmtrans.py&quot;, line 427, in callback
    self._scriptError(amount, total, key)
  File &quot;/usr/lib/python3.6/site-packages/dnf/yum/rpmtrans.py&quot;, line 551, in _scriptError
    name = pkg.name
AttributeError: &apos;NoneType&apos; object has no attribute &apos;name&apos;
FATAL ERROR: python callback ??? failed, aborting!</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10071182</commentid>
    <comment_count>5</comment_count>
    <who name="darrell pfeifer">darrellpf</who>
    <bug_when>2017-01-17 07:53:01 -0500</bug_when>
    <thetext>Running transaction
  Upgrading   : systemd-libs-232-8.fc26.x86_64                                                                            1/40 
  Upgrading   : systemd-pam-232-8.fc26.x86_64                                                                             2/40 
  Upgrading   : systemd-232-8.fc26.x86_64                                                                                 3/40 
  Upgrading   : selinux-policy-3.13.1-234.fc26.noarch                                                                     4/40 
  Upgrading   : publicsuffix-list-dafsa-20170116-1.fc26.noarch                                                            5/40 
  Upgrading   : libpsl-0.17.0-1.fc26.x86_64                                                                               6/40 
  Upgrading   : selinux-policy-targeted-3.13.1-234.fc26.noarch                                                            7/40 
  Upgrading   : systemd-udev-232-8.fc26.x86_64                                                                            8/40 
  Upgrading   : systemd-container-232-8.fc26.x86_64                                                                       9/40 
  Upgrading   : gnome-logs-3.23.4-1.fc26.x86_64                                                                          10/40 
  Upgrading   : shotwell-0.25.3-2.fc26.x86_64                                                                            11/40 
  Upgrading   : python3-pyatspi-2.20.3-1.fc26.noarch                                                                     12/40 
  Upgrading   : pyatspi-2.20.3-1.fc26.noarch                                                                             13/40 
  Upgrading   : publicsuffix-list-20170116-1.fc26.noarch                                                                 14/40 
  Upgrading   : libwsman1-2.6.3-1.git4391e5c.fc26.x86_64                                                                 15/40 
  Upgrading   : libtasn1-4.10-1.fc26.x86_64                                                                              16/40 
  Upgrading   : ibus-typing-booster-1.5.18-1.fc26.noarch                                                                 17/40 
  Cleanup     : selinux-policy-targeted-3.13.1-233.fc26.noarch                                                           18/40 
  Cleanup     : systemd-container-232-7.fc26.x86_64                                                                      19/40 
  Cleanup     : systemd-udev-232-7.fc26.x86_64                                                                           20/40 
  Cleanup     : systemd-pam-232-7.fc26.x86_64                                                                            21/40 
  Cleanup     : systemd-232-7.fc26.x86_64                                                                                22/40 
/var/tmp/rpm-tmp.tiGGCI: line 1: fg: no job control
error: %preun(systemd-udev-232-3.fc26.x86_64) scriptlet failed, exit status 1
Traceback (most recent call last):
  File &quot;/usr/lib/python3.6/site-packages/dnf/yum/rpmtrans.py&quot;, line 427, in callback
    self._scriptError(amount, total, key)
  File &quot;/usr/lib/python3.6/site-packages/dnf/yum/rpmtrans.py&quot;, line 551, in _scriptError
    name = pkg.name
AttributeError: &apos;NoneType&apos; object has no attribute &apos;name&apos;
FATAL ERROR: python callback ??? failed, aborting!</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10105143</commentid>
    <comment_count>6</comment_count>
    <who name="Igor Gnatenko">ignatenko</who>
    <bug_when>2017-01-30 04:01:42 -0500</bug_when>
    <thetext>*** Bug 1417546 has been marked as a duplicate of this bug. ***</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10187006</commentid>
    <comment_count>7</comment_count>
    <who name="Igor Gnatenko">ignatenko</who>
    <bug_when>2017-02-27 09:45:06 -0500</bug_when>
    <thetext>*** Bug 1425228 has been marked as a duplicate of this bug. ***</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10320950</commentid>
    <comment_count>8</comment_count>
    <who name="Jaroslav Mracek">jmracek</who>
    <bug_when>2017-04-10 11:24:56 -0400</bug_when>
    <thetext>Igor, please can you test it with latest dnf-2.3.0-1. I think the problem was already solved.</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>