<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.redhat.com/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.12068.1"
          urlbase="https://bugzilla.redhat.com/"
          
          maintainer="bugzilla-error-list@redhat.com"
>

    <bug>
          <bug_id>1396279</bug_id>
          
          <creation_ts>2016-11-17 16:03:00 -0500</creation_ts>
          <short_desc>[abrt] backintime-common: snapshots.py:1754:_free_space:IndexError: list index out of range</short_desc>
          <delta_ts>2017-04-09 21:50:31 -0400</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>2</classification_id>
          <classification>Fedora</classification>
          <product>Fedora</product>
          <component>backintime</component>
          <version>25</version>
          <rep_platform>x86_64</rep_platform>
          <op_sys>Unspecified</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>ERRATA</resolution>
          
          
          <bug_file_loc>https://retrace.fedoraproject.org/faf/reports/bthash/e0225f7f636364e24e25a07a2cb472464caca2b4</bug_file_loc>
          <status_whiteboard>abrt_hash:faf38ee0818ed8575274eec58dada45a4d4decca;VARIANT_ID=workstation;</status_whiteboard>
          <keywords></keywords>
          <priority>unspecified</priority>
          <bug_severity>unspecified</bug_severity>
          <target_milestone>---</target_milestone>
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Emmanuel Pacaud">emmanuel</reporter>
          <assigned_to name="hannes">johannes.lips</assigned_to>
          <cc>i</cc>
    
    
    <cc>johannes.lips</cc>
          <qa_contact name="Fedora Extras Quality Assurance">extras-qa</qa_contact>
          
          <cf_fixed_in>backintime-1.1.18-1.fc26 backintime-1.1.18-1.fc25 backintime-1.1.18-1.fc24</cf_fixed_in>
          <cf_doc_type>If docs needed, set a value</cf_doc_type>
          <cf_release_notes></cf_release_notes>
          <cf_story_points>---</cf_story_points>
          
          <cf_environment></cf_environment>
          <cf_last_closed>2017-04-06 09:43:45</cf_last_closed>
          <cf_type>---</cf_type>
          <cf_regression_status>---</cf_regression_status>
          <cf_mount_type>---</cf_mount_type>
          <cf_documentation_action>---</cf_documentation_action>
          <cf_crm></cf_crm>
          <cf_verified_branch></cf_verified_branch>
          <cf_category>---</cf_category>
          <cf_ovirt_team>---</cf_ovirt_team>
          
          <cf_cloudforms_team>---</cf_cloudforms_team>
          
          
          
          
          <target_release>---</target_release>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>9901356</commentid>
    <comment_count>0</comment_count>
    <who name="Emmanuel Pacaud">emmanuel</who>
    <bug_when>2016-11-17 16:03:48 -0500</bug_when>
    <thetext>Version-Release number of selected component:
backintime-common-1.1.12-2.fc25

Additional info:
reporter:       libreport-2.8.0
cmdline:        python3 /usr/share/backintime/common/backintime.py backup-job
executable:     /usr/share/backintime/common/backintime.py
kernel:         4.8.1-1.fc25.x86_64
pkg_fingerprint: 4089 D8F2 FDB1 9C98
pkg_vendor:     Fedora Project
runlevel:       N 5
type:           Python3
uid:            14316

Truncated backtrace:
snapshots.py:1754:_free_space:IndexError: list index out of range

Traceback (most recent call last):
  File &quot;/usr/share/backintime/common/backintime.py&quot;, line 865, in &lt;module&gt;
    start_app()
  File &quot;/usr/share/backintime/common/backintime.py&quot;, line 450, in start_app
    args.func(args)
  File &quot;/usr/share/backintime/common/backintime.py&quot;, line 634, in backupJob
    backup(args, False)
  File &quot;/usr/share/backintime/common/backintime.py&quot;, line 626, in backup
    ret = take_snapshot(cfg, force)
  File &quot;/usr/share/backintime/common/backintime.py&quot;, line 70, in take_snapshot
    ret = snapshots.Snapshots( cfg ).take_snapshot( force )
  File &quot;/usr/share/backintime/common/snapshots.py&quot;, line 1059, in take_snapshot
    self._free_space( now )
  File &quot;/usr/share/backintime/common/snapshots.py&quot;, line 1754, in _free_space
    if last_snapshot is not snapshots[-1]:
IndexError: list index out of range

Local variables in innermost frame:
min_free_space: 1024
last_snapshot: &apos;20161103-120004-197&apos;
keep_one_per_month: 12
self: &lt;snapshots.Snapshots object at 0x7f529f9b0550&gt;
keep_all: 2
min_free_inodes: 2
smart_remove: True
keep_one_per_day: 7
now: datetime.datetime(2016, 11, 3, 12, 0, 4, 501439)
snapshots: []
old_backup_id: &apos;20141101-000000-387&apos;
keep_one_per_week: 4</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9901357</commentid>
    <comment_count>1</comment_count>
      <attachid>1221634</attachid>
    <who name="Emmanuel Pacaud">emmanuel</who>
    <bug_when>2016-11-17 16:03:54 -0500</bug_when>
    <thetext>Created attachment 1221634
File: backtrace</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9901359</commentid>
    <comment_count>2</comment_count>
      <attachid>1221635</attachid>
    <who name="Emmanuel Pacaud">emmanuel</who>
    <bug_when>2016-11-17 16:03:57 -0500</bug_when>
    <thetext>Created attachment 1221635
File: environ</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9902671</commentid>
    <comment_count>3</comment_count>
    <who name="Raphael Groner">projects.rg</who>
    <bug_when>2016-11-18 04:04:56 -0500</bug_when>
    <thetext>Can you reproduce this crash? What did you do to get the backtrace?

&gt; Local variables in innermost frame:
…
&gt; snapshots: []

Maybe you&apos;ve manually deleted all of the snapshots from filesystem while backintime was running? Please use the GUI to remove obsolete snapshots.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9907438</commentid>
    <comment_count>4</comment_count>
    <who name="Emmanuel Pacaud">emmanuel</who>
    <bug_when>2016-11-21 03:32:11 -0500</bug_when>
    <thetext>(In reply to Raphael Groner from comment #3)
&gt; Can you reproduce this crash?

No.

&gt; What did you do to get the backtrace?

It is an ABRT report of a crash that probably happened during the automatic backup.
 
&gt; &gt; Local variables in innermost frame:
&gt; …
&gt; &gt; snapshots: []
&gt; 
&gt; Maybe you&apos;ve manually deleted all of the snapshots from filesystem while
&gt; backintime was running?

I didn&apos;t.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10295605</commentid>
    <comment_count>5</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-03-31 17:02:31 -0400</bug_when>
    <thetext>backintime-1.1.18-1.fc24 has been submitted as an update to Fedora 24. https://bodhi.fedoraproject.org/updates/FEDORA-2017-1941a828be</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10295606</commentid>
    <comment_count>6</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-03-31 17:02:39 -0400</bug_when>
    <thetext>backintime-1.1.18-1.fc25 has been submitted as an update to Fedora 25. https://bodhi.fedoraproject.org/updates/FEDORA-2017-f32fbc4dda</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10295608</commentid>
    <comment_count>7</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-03-31 17:02:44 -0400</bug_when>
    <thetext>backintime-1.1.18-1.fc26 has been submitted as an update to Fedora 26. https://bodhi.fedoraproject.org/updates/FEDORA-2017-a2fb994f60</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10297077</commentid>
    <comment_count>8</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-04-01 19:23:02 -0400</bug_when>
    <thetext>backintime-1.1.18-1.fc24 has been pushed to the Fedora 24 testing repository. If problems still persist, please make note of it in this bug report.
See https://fedoraproject.org/wiki/QA:Updates_Testing for
instructions on how to install test updates.
You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2017-1941a828be</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10297084</commentid>
    <comment_count>9</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-04-01 19:25:45 -0400</bug_when>
    <thetext>backintime-1.1.18-1.fc25 has been pushed to the Fedora 25 testing repository. If problems still persist, please make note of it in this bug report.
See https://fedoraproject.org/wiki/QA:Updates_Testing for
instructions on how to install test updates.
You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2017-f32fbc4dda</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10297150</commentid>
    <comment_count>10</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-04-01 20:52:18 -0400</bug_when>
    <thetext>backintime-1.1.18-1.fc26 has been pushed to the Fedora 26 testing repository. If problems still persist, please make note of it in this bug report.
See https://fedoraproject.org/wiki/QA:Updates_Testing for
instructions on how to install test updates.
You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2017-a2fb994f60</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10311032</commentid>
    <comment_count>11</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-04-06 09:43:45 -0400</bug_when>
    <thetext>backintime-1.1.18-1.fc26 has been pushed to the Fedora 26 stable repository. If problems still persist, please make note of it in this bug report.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10317662</commentid>
    <comment_count>12</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-04-09 17:51:22 -0400</bug_when>
    <thetext>backintime-1.1.18-1.fc25 has been pushed to the Fedora 25 stable repository. If problems still persist, please make note of it in this bug report.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10317852</commentid>
    <comment_count>13</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-04-09 21:50:31 -0400</bug_when>
    <thetext>backintime-1.1.18-1.fc24 has been pushed to the Fedora 24 stable repository. If problems still persist, please make note of it in this bug report.</thetext>
  </long_desc>
      
          <attachment
              isobsolete="0"
              ispatch="0"
              isprivate="0"
          >
            <attachid>1221634</attachid>
            <date>2016-11-17 16:03:00 -0500</date>
            <delta_ts>2016-11-17 16:03:54 -0500</delta_ts>
            <desc>File: backtrace</desc>
            <filename>backtrace</filename>
            <type>text/plain</type>
            <size>1269</size>
            <attacher name="Emmanuel Pacaud">emmanuel</attacher>
            
              <data encoding="base64">c25hcHNob3RzLnB5OjE3NTQ6X2ZyZWVfc3BhY2U6SW5kZXhFcnJvcjogbGlzdCBpbmRleCBvdXQg
b2YgcmFuZ2UKClRyYWNlYmFjayAobW9zdCByZWNlbnQgY2FsbCBsYXN0KToKICBGaWxlICIvdXNy
L3NoYXJlL2JhY2tpbnRpbWUvY29tbW9uL2JhY2tpbnRpbWUucHkiLCBsaW5lIDg2NSwgaW4gPG1v
ZHVsZT4KICAgIHN0YXJ0X2FwcCgpCiAgRmlsZSAiL3Vzci9zaGFyZS9iYWNraW50aW1lL2NvbW1v
bi9iYWNraW50aW1lLnB5IiwgbGluZSA0NTAsIGluIHN0YXJ0X2FwcAogICAgYXJncy5mdW5jKGFy
Z3MpCiAgRmlsZSAiL3Vzci9zaGFyZS9iYWNraW50aW1lL2NvbW1vbi9iYWNraW50aW1lLnB5Iiwg
bGluZSA2MzQsIGluIGJhY2t1cEpvYgogICAgYmFja3VwKGFyZ3MsIEZhbHNlKQogIEZpbGUgIi91
c3Ivc2hhcmUvYmFja2ludGltZS9jb21tb24vYmFja2ludGltZS5weSIsIGxpbmUgNjI2LCBpbiBi
YWNrdXAKICAgIHJldCA9IHRha2Vfc25hcHNob3QoY2ZnLCBmb3JjZSkKICBGaWxlICIvdXNyL3No
YXJlL2JhY2tpbnRpbWUvY29tbW9uL2JhY2tpbnRpbWUucHkiLCBsaW5lIDcwLCBpbiB0YWtlX3Nu
YXBzaG90CiAgICByZXQgPSBzbmFwc2hvdHMuU25hcHNob3RzKCBjZmcgKS50YWtlX3NuYXBzaG90
KCBmb3JjZSApCiAgRmlsZSAiL3Vzci9zaGFyZS9iYWNraW50aW1lL2NvbW1vbi9zbmFwc2hvdHMu
cHkiLCBsaW5lIDEwNTksIGluIHRha2Vfc25hcHNob3QKICAgIHNlbGYuX2ZyZWVfc3BhY2UoIG5v
dyApCiAgRmlsZSAiL3Vzci9zaGFyZS9iYWNraW50aW1lL2NvbW1vbi9zbmFwc2hvdHMucHkiLCBs
aW5lIDE3NTQsIGluIF9mcmVlX3NwYWNlCiAgICBpZiBsYXN0X3NuYXBzaG90IGlzIG5vdCBzbmFw
c2hvdHNbLTFdOgpJbmRleEVycm9yOiBsaXN0IGluZGV4IG91dCBvZiByYW5nZQoKTG9jYWwgdmFy
aWFibGVzIGluIGlubmVybW9zdCBmcmFtZToKbWluX2ZyZWVfc3BhY2U6IDEwMjQKbGFzdF9zbmFw
c2hvdDogJzIwMTYxMTAzLTEyMDAwNC0xOTcnCmtlZXBfb25lX3Blcl9tb250aDogMTIKc2VsZjog
PHNuYXBzaG90cy5TbmFwc2hvdHMgb2JqZWN0IGF0IDB4N2Y1MjlmOWIwNTUwPgprZWVwX2FsbDog
MgptaW5fZnJlZV9pbm9kZXM6IDIKc21hcnRfcmVtb3ZlOiBUcnVlCmtlZXBfb25lX3Blcl9kYXk6
IDcKbm93OiBkYXRldGltZS5kYXRldGltZSgyMDE2LCAxMSwgMywgMTIsIDAsIDQsIDUwMTQzOSkK
c25hcHNob3RzOiBbXQpvbGRfYmFja3VwX2lkOiAnMjAxNDExMDEtMDAwMDAwLTM4NycKa2VlcF9v
bmVfcGVyX3dlZWs6IDQK
</data>

          </attachment>
          <attachment
              isobsolete="0"
              ispatch="0"
              isprivate="0"
          >
            <attachid>1221635</attachid>
            <date>2016-11-17 16:03:00 -0500</date>
            <delta_ts>2016-11-17 16:03:57 -0500</delta_ts>
            <desc>File: environ</desc>
            <filename>environ</filename>
            <type>text/plain</type>
            <size>368</size>
            <attacher name="Emmanuel Pacaud">emmanuel</attacher>
            
              <data encoding="base64">U0hMVkw9MgpTU0hfQVVUSF9TT0NLPS90bXAvc3NoLVltTWdpbzVrNWJ6NC9hZ2VudC4xMjE4NgpE
QlVTX1NFU1NJT05fQlVTX0FERFJFU1M9dW5peDpwYXRoPS9ydW4vdXNlci8xNDMxNi9idXMKTEFO
Rz1mcl9GUi51dGY4ClhER19SVU5USU1FX0RJUj0vcnVuL3VzZXIvMTQzMTYKVVNFUj1wYWNhdWQK
TE9HTkFNRT1wYWNhdWQKXz0vdXNyL2Jpbi9zc2gtYWdlbnQKWERHX1NFU1NJT05fSUQ9MTYKU0hF
TEw9L2Jpbi9zaApESVNQTEFZPTowClNTSF9BR0VOVF9QSUQ9MTIxODgKUFdEPS9ob21lL3BhY2F1
ZApIT01FPS9ob21lL3BhY2F1ZApQQVRIPS91c3IvYmluOi9iaW4KR05PTUVfREVTS1RPUF9TRVNT
SU9OX0lEPXRoaXMtaXMtZGVwcmVjYXRlZAo=
</data>

          </attachment>
      

    </bug>

</bugzilla>