<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.redhat.com/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.12068.1"
          urlbase="https://bugzilla.redhat.com/"
          
          maintainer="bugzilla-error-list@redhat.com"
>

    <bug>
          <bug_id>1400565</bug_id>
          
          <creation_ts>2016-12-01 08:56:00 -0500</creation_ts>
          <short_desc>selinux-policy is preventing start of virtual machines</short_desc>
          <delta_ts>2016-12-08 13:22:16 -0500</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>2</classification_id>
          <classification>Fedora</classification>
          <product>Fedora</product>
          <component>selinux-policy</component>
          <version>25</version>
          <rep_platform>Unspecified</rep_platform>
          <op_sys>Unspecified</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>ERRATA</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords></keywords>
          <priority>unspecified</priority>
          <bug_severity>unspecified</bug_severity>
          <target_milestone>---</target_milestone>
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Jakub Jelen">jjelen</reporter>
          <assigned_to name="Lukas Vrabec">lvrabec</assigned_to>
          <cc>dhgutteridge</cc>
    
    
    <cc>dominick.grift</cc>
    
    
    <cc>dwalsh</cc>
    
    
    <cc>hancock</cc>
    
    
    <cc>lvrabec</cc>
    
    
    <cc>mgrepl</cc>
    
    
    <cc>plautrba</cc>
    
    
    <cc>pmoore</cc>
    
    
    <cc>ssekidde</cc>
          <qa_contact name="Fedora Extras Quality Assurance">extras-qa</qa_contact>
          
          <cf_fixed_in>selinux-policy-3.13.1-225.1.fc25</cf_fixed_in>
          <cf_doc_type>If docs needed, set a value</cf_doc_type>
          <cf_release_notes></cf_release_notes>
          <cf_story_points>---</cf_story_points>
          
          <cf_environment></cf_environment>
          <cf_last_closed>2016-12-08 13:22:16</cf_last_closed>
          <cf_type>Bug</cf_type>
          <cf_regression_status>---</cf_regression_status>
          <cf_mount_type>---</cf_mount_type>
          <cf_documentation_action>---</cf_documentation_action>
          <cf_crm></cf_crm>
          <cf_verified_branch></cf_verified_branch>
          <cf_category>---</cf_category>
          <cf_ovirt_team>---</cf_ovirt_team>
          
          <cf_cloudforms_team>---</cf_cloudforms_team>
          
          
          
          
          <target_release>---</target_release>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>9947440</commentid>
    <comment_count>0</comment_count>
    <who name="Jakub Jelen">jjelen</who>
    <bug_when>2016-12-01 08:56:28 -0500</bug_when>
    <thetext>Description of problem:
Start of the virtual machine fails

Version-Release number of selected component (if applicable):
systemd-231-10.fc25.x86_64
selinux-policy-3.13.1-225.fc25.noarch
virt-manager-1.4.0-4.fc25.noarch

How reproducible:
always

Steps to Reproduce:
1. Try to start virtual machine in virt-manager

Actual results:
Errors below, USER_AVCs

Expected results:
Running virtual machine

Additional info:
### Error from virt-manager:
Error starting domain: SELinux policy denies access.

Traceback (most recent call last):
  File &quot;/usr/share/virt-manager/virtManager/asyncjob.py&quot;, line 88, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File &quot;/usr/share/virt-manager/virtManager/asyncjob.py&quot;, line 124, in tmpcb
    callback(*args, **kwargs)
  File &quot;/usr/share/virt-manager/virtManager/libvirtobject.py&quot;, line 83, in newfn
    ret = fn(self, *args, **kwargs)
  File &quot;/usr/share/virt-manager/virtManager/domain.py&quot;, line 1404, in startup
    self._backend.create()
  File &quot;/usr/lib64/python2.7/site-packages/libvirt.py&quot;, line 1035, in create
    if ret == -1: raise libvirtError (&apos;virDomainCreate() failed&apos;, dom=self)
libvirtError: SELinux policy denies access.

### AVCs:
----
time-&gt;Thu Dec  1 14:44:10 2016
type=USER_AVC msg=audit(1480599850.217:4718): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg=&apos;avc:  denied  { start } for auid=n/a uid=0 gid=0 path=&quot;/run/systemd/transient/machine-qemu\x2d4\x2dfedora26.scope&quot; cmdline=&quot;/usr/lib/systemd/systemd-machined&quot; scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:object_r:init_var_run_t:s0 tclass=service  exe=&quot;/usr/lib/systemd/systemd&quot; sauid=0 hostname=? addr=? terminal=?&apos;
----
time-&gt;Thu Dec  1 14:51:04 2016
type=USER_AVC msg=audit(1480600264.196:4790): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg=&apos;avc:  denied  { start } for auid=n/a uid=0 gid=0 path=&quot;/run/systemd/transient/machine-qemu\x2d6\x2drhel6.8.scope&quot; cmdline=&quot;/usr/lib/systemd/systemd-machined&quot; scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:object_r:init_var_run_t:s0 tclass=service  exe=&quot;/usr/lib/systemd/systemd&quot; sauid=0 hostname=? addr=? terminal=?&apos;</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9948995</commentid>
    <comment_count>1</comment_count>
    <who name="David H. Gutteridge">dhgutteridge</who>
    <bug_when>2016-12-01 16:08:54 -0500</bug_when>
    <thetext>I&apos;m seeing the same issue. (I&apos;ve reverted to selinux-policy-3.13.1-224.fc25.noarch.)</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9956776</commentid>
    <comment_count>2</comment_count>
    <who name="Robert Hancock">hancock</who>
    <bug_when>2016-12-05 11:00:31 -0500</bug_when>
    <thetext>Saw the same regression. Had to roll back to selinux-policy-3.13.1-224.fc25.noarch. Not sure why this has been marked as fixed in 3.13.1-225.fc25 when that was the version that introduced the error.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9956812</commentid>
    <comment_count>3</comment_count>
    <who name="Jakub Jelen">jjelen</who>
    <bug_when>2016-12-05 11:08:07 -0500</bug_when>
    <thetext>(In reply to Robert Hancock from comment #2)
&gt; Saw the same regression. Had to roll back to
&gt; selinux-policy-3.13.1-224.fc25.noarch. Not sure why this has been marked as
&gt; fixed in 3.13.1-225.fc25 when that was the version that introduced the error.

Note the 225.1 in the &quot;selinux-policy-3.13.1-225.1.fc25&quot;</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9957000</commentid>
    <comment_count>4</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-12-05 12:01:37 -0500</bug_when>
    <thetext>selinux-policy-3.13.1-225.1.fc25 has been submitted as an update to Fedora 25. https://bodhi.fedoraproject.org/updates/FEDORA-2016-e3864b8972</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9957478</commentid>
    <comment_count>5</comment_count>
    <who name="David H. Gutteridge">dhgutteridge</who>
    <bug_when>2016-12-05 15:06:45 -0500</bug_when>
    <thetext>Confirming selinux-policy-3.13.1-225.1.fc25 fixes the issue for me.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9962618</commentid>
    <comment_count>6</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-12-06 21:25:14 -0500</bug_when>
    <thetext>selinux-policy-3.13.1-225.1.fc25 has been pushed to the Fedora 25 testing repository. If problems still persist, please make note of it in this bug report.
See https://fedoraproject.org/wiki/QA:Updates_Testing for
instructions on how to install test updates.
You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2016-e3864b8972</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9969140</commentid>
    <comment_count>7</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-12-08 13:22:16 -0500</bug_when>
    <thetext>selinux-policy-3.13.1-225.1.fc25 has been pushed to the Fedora 25 stable repository. If problems still persist, please make note of it in this bug report.</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>