<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.redhat.com/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.12068.1"
          urlbase="https://bugzilla.redhat.com/"
          
          maintainer="bugzilla-error-list@redhat.com"
>

    <bug>
          <bug_id>1428492</bug_id>
          
          <creation_ts>2017-03-02 11:52:00 -0500</creation_ts>
          <short_desc>Cloud-init is starting before multi-user.target still</short_desc>
          <delta_ts>2017-03-20 18:19:58 -0400</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>2</classification_id>
          <classification>Fedora</classification>
          <product>Fedora</product>
          <component>cloud-init</component>
          <version>25</version>
          <rep_platform>x86_64</rep_platform>
          <op_sys>Linux</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>ERRATA</resolution>
          
          <see_also>https://bugzilla.redhat.com/show_bug.cgi?id=1393094</see_also>
    
    
    
    <see_also>https://bugzilla.redhat.com/show_bug.cgi?id=1400249</see_also>
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords>Reopened</keywords>
          <priority>unspecified</priority>
          <bug_severity>urgent</bug_severity>
          <target_milestone>---</target_milestone>
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Bekzot Azimov">bekzot.asimov</reporter>
          <assigned_to name="Garrett Holmstrom">gholms</assigned_to>
          <cc>adimania</cc>
    
    
    <cc>apevec</cc>
    
    
    <cc>bekzot.asimov</cc>
    
    
    <cc>gholms</cc>
    
    
    <cc>Jan.van.Eldik</cc>
    
    
    <cc>lars</cc>
    
    
    <cc>shardy</cc>
    
    
    <cc>sijis.aviles</cc>
    
    
    <cc>s</cc>
          <qa_contact name="Fedora Extras Quality Assurance">extras-qa</qa_contact>
          
          <cf_fixed_in>cloud-init-0.7.9-4.fc26</cf_fixed_in>
          <cf_doc_type>If docs needed, set a value</cf_doc_type>
          <cf_release_notes></cf_release_notes>
          <cf_story_points>---</cf_story_points>
          
          <cf_environment></cf_environment>
          <cf_last_closed>2017-03-20 18:19:58</cf_last_closed>
          <cf_type>Bug</cf_type>
          <cf_regression_status>---</cf_regression_status>
          <cf_mount_type>---</cf_mount_type>
          <cf_documentation_action>---</cf_documentation_action>
          <cf_crm></cf_crm>
          <cf_verified_branch></cf_verified_branch>
          <cf_category>---</cf_category>
          <cf_ovirt_team>---</cf_ovirt_team>
          
          <cf_cloudforms_team>---</cf_cloudforms_team>
          
          
          
          
          <target_release>---</target_release>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>10202867</commentid>
    <comment_count>0</comment_count>
    <who name="Bekzot Azimov">bekzot.asimov</who>
    <bug_when>2017-03-02 11:52:24 -0500</bug_when>
    <thetext>Description of problem:
We have seen a bugfix for cloud-init that says start after multi-user.target but it still trying to launch before and causing different problems.

Version-Release number of selected component (if applicable):


How reproducible:
Always

Steps to Reproduce:
1. Launch aws fedora 25 image gp2 hvm
2. Run a command: sudo systemd-analyze critical-chain multi-user.target

Actual results:

multi-user.target @5.760s
└─getty.target @5.760s
  └─serial-getty@ttyS0.service @5.759s
    └─systemd-user-sessions.service @5.545s +20ms
      └─cloud-init.service @2.592s +2.947s
        └─cloud-init-local.service @441ms +2.148s
          └─local-fs.target @431ms
            └─local-fs-pre.target @431ms
              └─systemd-tmpfiles-setup-dev.service @384ms +46ms
                └─kmod-static-nodes.service @341ms +35ms
                  └─systemd-journald.socket
                    └─-.mount
                      └─system.slice
                        └─-.slice

Expected results:
cloud-init.service nor cloud-init-local.service should be there.

Additional info:
AMI starts up fine, but causing collision issues later when we deploy new things.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10203392</commentid>
    <comment_count>1</comment_count>
    <who name="Bekzot Azimov">bekzot.asimov</who>
    <bug_when>2017-03-02 13:59:24 -0500</bug_when>
    <thetext>Mar  1 21:34:34 ip-173-20-78-118 systemd: multi-user.target: Found dependency on cloud-init.target/start
Mar  1 21:34:34 ip-173-20-78-118 systemd: multi-user.target: Found dependency on cloud-final.service/start
Mar  1 21:34:34 ip-173-20-78-118 systemd: multi-user.target: Found dependency on multi-user.target/start
Mar  1 21:34:34 ip-173-20-78-118 systemd: multi-user.target: Breaking ordering cycle by deleting job cloud-init.target/start
Mar  1 21:34:34 ip-172-20-78-118 systemd: cloud-init.target: Job cloud-init.target/start deleted to break ordering cycle starting with multi-user.target/start</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10203664</commentid>
    <comment_count>2</comment_count>
    <who name="Bekzot Azimov">bekzot.asimov</who>
    <bug_when>2017-03-02 15:07:09 -0500</bug_when>
    <thetext>cloud-init version: cloud-init-0.7.8-5.fc25.noarch</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10203733</commentid>
    <comment_count>3</comment_count>
    <who name="Bekzot Azimov">bekzot.asimov</who>
    <bug_when>2017-03-02 15:31:58 -0500</bug_when>
    <thetext>This happens on ami-56a08841 us-east-1 image of fedora 25. Image comes up fine, but whenever I deploy some new services it hangs, and I can see above ordering cycle issue in the /var/log/messages.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10234383</commentid>
    <comment_count>4</comment_count>
    <who name="Bekzot Azimov">bekzot.asimov</who>
    <bug_when>2017-03-13 15:03:20 -0400</bug_when>
    <thetext>I think we found the issue. We required cloud-final.service on our services which tries to start cloud-final.service. Cloud-final has a flag to start after multi-user.target, which causes collision.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10234384</commentid>
    <comment_count>5</comment_count>
    <who name="Bekzot Azimov">bekzot.asimov</who>
    <bug_when>2017-03-13 15:03:37 -0400</bug_when>
    <thetext>I think we found the issue. We required cloud-final.service on our services which tries to start cloud-final.service. Cloud-final has a flag to start after multi-user.target, which causes collision.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10234485</commentid>
    <comment_count>6</comment_count>
    <who name="Bekzot Azimov">bekzot.asimov</who>
    <bug_when>2017-03-13 15:46:40 -0400</bug_when>
    <thetext>Now whoever requires cloud-init in their service will face this issue. Is this how we want it? Or should there be a patch?</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10238240</commentid>
    <comment_count>7</comment_count>
    <who name="Lars Kellogg-Stedman">lars</who>
    <bug_when>2017-03-14 11:16:49 -0400</bug_when>
    <thetext>There is a scratch build available at https://koji.fedoraproject.org/koji/taskinfo?taskID=18380550 that may resolve this problem.  Please give it a try and let me know if it resolves this issue.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10239755</commentid>
    <comment_count>8</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-03-14 19:35:26 -0400</bug_when>
    <thetext>cloud-init-0.7.9-4.fc26 has been submitted as an update to Fedora 26. https://bodhi.fedoraproject.org/updates/FEDORA-2017-83671c0fa0</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10240046</commentid>
    <comment_count>9</comment_count>
    <who name="Bekzot Azimov">bekzot.asimov</who>
    <bug_when>2017-03-14 22:07:54 -0400</bug_when>
    <thetext>Thank you Lars Kellogg-Stedman. This is exactly what is happening when I do not require cloud-init in my services 1400249. Incorrect networking.service looks like being addressed with patch to cloud-init-0.7.8-6.fc25. We will just wait for this package then.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10240059</commentid>
    <comment_count>10</comment_count>
    <who name="Bekzot Azimov">bekzot.asimov</who>
    <bug_when>2017-03-14 22:16:04 -0400</bug_when>
    <thetext>1400249 will resolve it. I will close my report.

*** This bug has been marked as a duplicate of bug 1400249 ***</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10240325</commentid>
    <comment_count>11</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-03-15 00:24:54 -0400</bug_when>
    <thetext>cloud-init-0.7.9-4.fc26 has been pushed to the Fedora 26 testing repository. If problems still persist, please make note of it in this bug report.
See https://fedoraproject.org/wiki/QA:Updates_Testing for
instructions on how to install test updates.
You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2017-83671c0fa0</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10256090</commentid>
    <comment_count>12</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-03-20 18:19:58 -0400</bug_when>
    <thetext>cloud-init-0.7.9-4.fc26 has been pushed to the Fedora 26 stable repository. If problems still persist, please make note of it in this bug report.</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>