<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.redhat.com/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.12068.1"
          urlbase="https://bugzilla.redhat.com/"
          
          maintainer="bugzilla-error-list@redhat.com"
>

    <bug>
          <bug_id>1209862</bug_id>
          
          <creation_ts>2015-04-08 07:19:00 -0400</creation_ts>
          <short_desc>Installing dnf-plugins-extras causes errors about /var/lib/dnf/plugins/local</short_desc>
          <delta_ts>2017-04-19 11:06:51 -0400</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>2</classification_id>
          <classification>Fedora</classification>
          <product>Fedora</product>
          <component>dnf-plugins-extras</component>
          <version>26</version>
          <rep_platform>Unspecified</rep_platform>
          <op_sys>Unspecified</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>NEXTRELEASE</resolution>
          
          <see_also>https://bugzilla.redhat.com/show_bug.cgi?id=1219283</see_also>
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords>Reopened, Triaged</keywords>
          <priority>unspecified</priority>
          <bug_severity>medium</bug_severity>
          <target_milestone>---</target_milestone>
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Tom Hughes">tom</reporter>
          <assigned_to>rpm-software-management</assigned_to>
          <cc>cks-rhbugzilla</cc>
    
    
    <cc>igeorgex</cc>
    
    
    <cc>jkadlcik</cc>
    
    
    <cc>jmracek</cc>
    
    
    <cc>liblit</cc>
    
    
    <cc>mluscon</cc>
    
    
    <cc>packaging-team-maint</cc>
    
    
    <cc>rocketraman</cc>
    
    
    <cc>vmukhame</cc>
    
    
    <cc>vondruch</cc>
          <qa_contact name="Fedora Extras Quality Assurance">extras-qa</qa_contact>
          
          <cf_fixed_in></cf_fixed_in>
          <cf_doc_type>Bug Fix</cf_doc_type>
          <cf_release_notes></cf_release_notes>
          <cf_story_points>---</cf_story_points>
          
          <cf_environment></cf_environment>
          <cf_last_closed>2017-04-19 11:06:51</cf_last_closed>
          <cf_type>Bug</cf_type>
          <cf_regression_status>---</cf_regression_status>
          <cf_mount_type>---</cf_mount_type>
          <cf_documentation_action>---</cf_documentation_action>
          <cf_crm></cf_crm>
          <cf_verified_branch></cf_verified_branch>
          <cf_category>---</cf_category>
          <cf_ovirt_team>---</cf_ovirt_team>
          
          <cf_cloudforms_team>---</cf_cloudforms_team>
          
          
          
          
          <target_release>---</target_release>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>8122839</commentid>
    <comment_count>0</comment_count>
    <who name="Tom Hughes">tom</who>
    <bug_when>2015-04-08 07:19:13 -0400</bug_when>
    <thetext>After installing dnf-plugins-extras most dnf commands complain with:

Failed to synchronize cache for repo &apos;_local&apos; from &apos;file:///var/lib/dnf/plugins/local&apos;: Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.

Apparently python-dnf-plugins-extras-local configures a (hidden and not mentioned in /etc/yum.repos.d) repository based on the non-existent /var/lib/dnf/plugins/local directory.

This is with dnf-plugins-extras 0.0.6-2.fc22.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>8390851</commentid>
    <comment_count>1</comment_count>
    <who name="Radek Holy">rholy</who>
    <bug_when>2015-06-30 02:56:50 -0400</bug_when>
    <thetext>*** Bug 1236745 has been marked as a duplicate of this bug. ***</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>8393479</commentid>
    <comment_count>2</comment_count>
    <who name="Igor Gnatenko">ignatenko</who>
    <bug_when>2015-06-30 12:44:11 -0400</bug_when>
    <thetext>Probably in this case I should do in post script `/usr/bin/createrepo_c /var/lib/dnf/plugins/local`.

Radek, what do you think?</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>8396667</commentid>
    <comment_count>3</comment_count>
    <who name="Radek Holy">rholy</who>
    <bug_when>2015-07-01 04:31:19 -0400</bug_when>
    <thetext>Maybe, or create the repository once the plugin finds out that it does not exist (do I understand correctly that this is what yum-plugin-local does?), or don&apos;t add the repository if it does not exist. I&apos;m not sure what is the best solution.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9523719</commentid>
    <comment_count>4</comment_count>
    <who name="Fedora End Of Life">jkurik</who>
    <bug_when>2016-07-19 09:40:07 -0400</bug_when>
    <thetext>Fedora 22 changed to end-of-life (EOL) status on 2016-07-19. Fedora 22 is
no longer maintained, which means that it will not receive any further
security or bug fix updates. As a result we are closing this bug.

If you can reproduce this bug against a currently maintained version of
Fedora please feel free to reopen this bug against that version. If you
are unable to reopen this bug, please file a new report against the
current release. If you experience problems, please add a comment to this
bug.

Thank you for reporting this bug and we are sorry it could not be fixed.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9942377</commentid>
    <comment_count>5</comment_count>
    <who name="Igor Gnatenko">ignatenko</who>
    <bug_when>2016-11-30 05:57:13 -0500</bug_when>
    <thetext>*** Bug 1357943 has been marked as a duplicate of this bug. ***</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9942379</commentid>
    <comment_count>6</comment_count>
    <who name="Igor Gnatenko">ignatenko</who>
    <bug_when>2016-11-30 05:57:26 -0500</bug_when>
    <thetext>*** Bug 1236747 has been marked as a duplicate of this bug. ***</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10190577</commentid>
    <comment_count>7</comment_count>
    <who name="Fedora End Of Life">jkurik</who>
    <bug_when>2017-02-28 04:42:40 -0500</bug_when>
    <thetext>This bug appears to have been reported against &apos;rawhide&apos; during the Fedora 26 development cycle.
Changing version to &apos;26&apos;.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10346315</commentid>
    <comment_count>8</comment_count>
    <who name="Jaroslav Mracek">jmracek</who>
    <bug_when>2017-04-19 11:06:51 -0400</bug_when>
    <thetext>I added a commit https://github.com/rpm-software-management/dnf-plugins-extras/commit/c20ca34df9ebca8714c7d347db98db392ffe9dc0 that should help. The patch will be released in dnf-plugins-core-2.0.0 probably next week into rawhide and fc26. But at the present time it can be tested from out test repository: &quot;dnf copr enable rpmsoftwaremanagement/dnf-nightly&quot;</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>