<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.redhat.com/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.12068.1"
          urlbase="https://bugzilla.redhat.com/"
          
          maintainer="bugzilla-error-list@redhat.com"
>

    <bug>
          <bug_id>1392591</bug_id>
          
          <creation_ts>2016-11-07 15:38:00 -0500</creation_ts>
          <short_desc>missing Requires on systemd-udev</short_desc>
          <delta_ts>2017-03-07 03:07:40 -0500</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>2</classification_id>
          <classification>Fedora</classification>
          <product>Fedora</product>
          <component>python-blivet</component>
          <version>26</version>
          <rep_platform>Unspecified</rep_platform>
          <op_sys>Unspecified</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>ERRATA</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords></keywords>
          <priority>unspecified</priority>
          <bug_severity>unspecified</bug_severity>
          <target_milestone>---</target_milestone>
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Dennis Gilmore">dennis</reporter>
          <assigned_to name="Vojtech Trefny">vtrefny</assigned_to>
          <cc>anaconda-maint-list</cc>
    
    
    <cc>blivet-maint-list</cc>
    
    
    <cc>g.kaviyarasu</cc>
    
    
    <cc>jonathan</cc>
    
    
    <cc>kevin</cc>
    
    
    <cc>mkolman</cc>
    
    
    <cc>vanmeeuwen+fedora</cc>
    
    
    <cc>vponcova</cc>
    
    
    <cc>vtrefny</cc>
          <qa_contact name="Fedora Extras Quality Assurance">extras-qa</qa_contact>
          
          <cf_fixed_in>python-blivet-2.1.7-3</cf_fixed_in>
          <cf_doc_type>If docs needed, set a value</cf_doc_type>
          <cf_release_notes></cf_release_notes>
          <cf_story_points>---</cf_story_points>
          
          <cf_environment></cf_environment>
          <cf_last_closed>2017-03-07 03:07:40</cf_last_closed>
          <cf_type>Bug</cf_type>
          <cf_regression_status>---</cf_regression_status>
          <cf_mount_type>---</cf_mount_type>
          <cf_documentation_action>---</cf_documentation_action>
          <cf_crm></cf_crm>
          <cf_verified_branch></cf_verified_branch>
          <cf_category>---</cf_category>
          <cf_ovirt_team>---</cf_ovirt_team>
          
          <cf_cloudforms_team>---</cf_cloudforms_team>
          
          
          
          
          <target_release>---</target_release>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>9868640</commentid>
    <comment_count>0</comment_count>
    <who name="Dennis Gilmore">dennis</who>
    <bug_when>2016-11-07 15:38:52 -0500</bug_when>
    <thetext>Description of problem:

Livecd creation failed due to udevadm being missing. it ended up that the only reason udevadm was being pulled in was NetworkManager having a dep on udev. hoever with commit http://pkgs.fedoraproject.org/cgit/rpms/NetworkManager.git/commit/?id=ce85c6f3ef984d17cfc3cae7f883ae3521ebb961 the Requires: udev was removed resulting in udevadm no longer being available in the installer environment for anaconda to execute  as anaconda calls the command it needs to add a requires on udev or systemd-udev in order to make sure a command it executes is available

2016-11-07 11:24:06,245 INFO livemedia-creator: import imp
2016-11-07 11:24:06,245 INFO livemedia-creator: Starting installer, one moment...
2016-11-07 11:24:06,246 INFO livemedia-creator: terminal size detection failed, using default width
2016-11-07 11:24:06,246 INFO livemedia-creator: anaconda 26.10-1 for Fedora-Workstation-Live Rawhide (pre-release) started.
2016-11-07 11:24:06,292 INFO livemedia-creator: Traceback (most recent call last):
2016-11-07 11:24:06,292 INFO livemedia-creator: File &quot;/usr/sbin/anaconda&quot;, line 486, in &lt;module&gt;
2016-11-07 11:24:06,292 INFO livemedia-creator: ksdata = startup_utils.parse_kickstart(opts, addon_paths)
2016-11-07 11:24:06,292 INFO livemedia-creator: File &quot;/usr/lib64/python3.5/site-packages/pyanaconda/startup_utils.py&quot;, line 447, in parse_kickstart
2016-11-07 11:24:06,293 INFO livemedia-creator: ksdata = kickstart.parseKickstart(ks)
2016-11-07 11:24:06,293 INFO livemedia-creator: File &quot;/usr/lib64/python3.5/site-packages/pyanaconda/kickstart.py&quot;, line 2152, in parseKickstart
2016-11-07 11:24:06,293 INFO livemedia-creator: udev.trigger(subsystem=&quot;block&quot;, action=&quot;change&quot;)
2016-11-07 11:24:06,293 INFO livemedia-creator: File &quot;/usr/lib/python3.5/site-packages/blivet/udev.py&quot;, line 81, in trigger
2016-11-07 11:24:06,294 INFO livemedia-creator: util.run_program([&quot;udevadm&quot;] + argv)
2016-11-07 11:24:06,294 INFO livemedia-creator: File &quot;/usr/lib/python3.5/site-packages/blivet/util.py&quot;, line 215, in run_program
2016-11-07 11:24:06,294 INFO livemedia-creator: return _run_program(*args, **kwargs)[0]
2016-11-07 11:24:06,294 INFO livemedia-creator: File &quot;/usr/lib/python3.5/site-packages/blivet/util.py&quot;, line 189, in _run_program
2016-11-07 11:24:06,295 INFO livemedia-creator: preexec_fn=chroot, cwd=root, env=env)
2016-11-07 11:24:06,295 INFO livemedia-creator: File &quot;/usr/lib64/python3.5/subprocess.py&quot;, line 947, in __init__
2016-11-07 11:24:06,295 INFO livemedia-creator: restore_signals, start_new_session)
2016-11-07 11:24:06,295 INFO livemedia-creator: File &quot;/usr/lib64/python3.5/subprocess.py&quot;, line 1551, in _execute_child
2016-11-07 11:24:06,295 INFO livemedia-creator: raise child_exception_type(errno_num, err_msg)
2016-11-07 11:24:06,296 INFO livemedia-creator: FileNotFoundError: [Errno 2] No such file or directory: &apos;udevadm&apos;
2016-11-07 11:24:06,394 ERROR livemedia-creator: Running anaconda failed: process &apos;[&apos;anaconda&apos;, &apos;--kickstart&apos;, &apos;/tmp/koji-image-f26-build-16334204.ks&apos;, &apos;--cmdline&apos;, &apos;--dirinstall&apos;, &apos;--remotelog&apos;, &apos;127.0.0.1:46103&apos;]&apos; exited with status 1
2016-11-07 11:25:04,290 ERROR livemedia-creator: Install failed: novirt_install failed</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9908181</commentid>
    <comment_count>1</comment_count>
    <who name="Martin Kolman">mkolman</who>
    <bug_when>2016-11-21 07:36:50 -0500</bug_when>
    <thetext>Seems to be Blivet that&apos;s calling udevadm, so reassigning:

2016-11-07 11:24:06,293 INFO livemedia-creator: File &quot;/usr/lib/python3.5/site-packages/blivet/udev.py&quot;, line 81, in trigger
2016-11-07 11:24:06,294 INFO livemedia-creator: util.run_program([&quot;udevadm&quot;] + argv)</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10171657</commentid>
    <comment_count>2</comment_count>
    <who name="Dennis Gilmore">dennis</who>
    <bug_when>2017-02-21 11:29:57 -0500</bug_when>
    <thetext>I think this is fixed and this bug can be closed</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10191535</commentid>
    <comment_count>3</comment_count>
    <who name="Fedora End Of Life">jkurik</who>
    <bug_when>2017-02-28 05:34:39 -0500</bug_when>
    <thetext>This bug appears to have been reported against &apos;rawhide&apos; during the Fedora 26 development cycle.
Changing version to &apos;26&apos;.</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>