<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.redhat.com/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.12068.1"
          urlbase="https://bugzilla.redhat.com/"
          
          maintainer="bugzilla-error-list@redhat.com"
>

    <bug>
          <bug_id>1416362</bug_id>
          
          <creation_ts>2017-01-25 06:15:00 -0500</creation_ts>
          <short_desc>sepolicy booleans -b ... tracebacks</short_desc>
          <delta_ts>2017-04-01 13:05:34 -0400</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>2</classification_id>
          <classification>Fedora</classification>
          <product>Fedora</product>
          <component>libselinux</component>
          <version>26</version>
          <rep_platform>All</rep_platform>
          <op_sys>Linux</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>ERRATA</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords></keywords>
          <priority>medium</priority>
          <bug_severity>medium</bug_severity>
          <target_milestone>---</target_milestone>
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Milos Malik">mmalik</reporter>
          <assigned_to name="Petr Lautrbach">plautrba</assigned_to>
          <cc>dwalsh</cc>
    
    
    <cc>mgrepl</cc>
    
    
    <cc>plautrba</cc>
    
    
    <cc>pmoore</cc>
    
    
    <cc>vmojzis</cc>
          <qa_contact name="Fedora Extras Quality Assurance">extras-qa</qa_contact>
          
          <cf_fixed_in>libselinux-2.6-3.fc26</cf_fixed_in>
          <cf_doc_type>If docs needed, set a value</cf_doc_type>
          <cf_release_notes></cf_release_notes>
          <cf_story_points>---</cf_story_points>
          
          <cf_environment></cf_environment>
          <cf_last_closed>2017-04-01 13:05:34</cf_last_closed>
          <cf_type>Bug</cf_type>
          <cf_regression_status>---</cf_regression_status>
          <cf_mount_type>---</cf_mount_type>
          <cf_documentation_action>---</cf_documentation_action>
          <cf_crm></cf_crm>
          <cf_verified_branch></cf_verified_branch>
          <cf_category>---</cf_category>
          <cf_ovirt_team>---</cf_ovirt_team>
          
          <cf_cloudforms_team>---</cf_cloudforms_team>
          
          
          
          
          <target_release>---</target_release>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>10095109</commentid>
    <comment_count>0</comment_count>
    <who name="Milos Malik">mmalik</who>
    <bug_when>2017-01-25 06:15:06 -0500</bug_when>
    <thetext>Description of problem:
* the tool ends with a traceback no matter what boolean you use

Version-Release number of selected component (if applicable):
checkpolicy-2.6-0.1.fc25.x86_64
libselinux-2.6-0.1.fc25.x86_64
libselinux-python-2.6-0.1.fc25.x86_64
libselinux-python3-2.6-0.1.fc25.x86_64
libselinux-utils-2.6-0.1.fc25.x86_64
libsemanage-2.6-0.2.fc25.x86_64
libsemanage-python-2.6-0.2.fc25.x86_64
libsemanage-python3-2.6-0.2.fc25.x86_64
libsepol-2.6-0.2.fc25.x86_64
policycoreutils-2.6-0.5.fc25.x86_64
policycoreutils-devel-2.6-0.5.fc25.x86_64
policycoreutils-gui-2.6-0.5.fc25.x86_64
policycoreutils-python-2.6-0.5.fc25.x86_64
policycoreutils-python3-2.6-0.5.fc25.x86_64
policycoreutils-python-utils-2.6-0.5.fc25.x86_64
setools-console-4.0.1-0.2.fc25.x86_64
setools-python3-4.0.1-0.2.fc25.x86_64

How reproducible:
* always

Steps to Reproduce:
# sepolicy booleans -b nis_enabled
Traceback (most recent call last):
  File &quot;/usr/bin/sepolicy&quot;, line 699, in &lt;module&gt;
    args = parser.parse_args(args=parser_args)
  File &quot;/usr/lib64/python3.5/argparse.py&quot;, line 1726, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File &quot;/usr/lib64/python3.5/argparse.py&quot;, line 1758, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File &quot;/usr/lib64/python3.5/argparse.py&quot;, line 1946, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File &quot;/usr/lib64/python3.5/argparse.py&quot;, line 1923, in consume_positionals
    take_action(action, args)
  File &quot;/usr/lib64/python3.5/argparse.py&quot;, line 1832, in take_action
    action(self, namespace, argument_values, option_string)
  File &quot;/usr/lib64/python3.5/argparse.py&quot;, line 1129, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File &quot;/usr/lib64/python3.5/argparse.py&quot;, line 1758, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File &quot;/usr/lib64/python3.5/argparse.py&quot;, line 1964, in _parse_known_args
    start_index = consume_optional(start_index)
  File &quot;/usr/lib64/python3.5/argparse.py&quot;, line 1904, in consume_optional
    take_action(action, args, option_string)
  File &quot;/usr/lib64/python3.5/argparse.py&quot;, line 1832, in take_action
    action(self, namespace, argument_values, option_string)
  File &quot;/usr/bin/sepolicy&quot;, line 96, in __call__
    raise ValueError(&quot;%s must be an SELinux boolean:\nValid boolean: %s&quot; % (v, &quot;, &quot;.join(booleans)))
TypeError: sequence item 0: expected str instance, bytes found
#

Actual results:
* traceback

Expected results:
* no traceback</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10237205</commentid>
    <comment_count>1</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-03-14 08:14:38 -0400</bug_when>
    <thetext>libselinux-2.6-3.fc26 has been submitted as an update to Fedora 26. https://bodhi.fedoraproject.org/updates/FEDORA-2017-c50bcf22f5</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10240299</commentid>
    <comment_count>2</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-03-15 00:23:12 -0400</bug_when>
    <thetext>libselinux-2.6-3.fc26 has been pushed to the Fedora 26 testing repository. If problems still persist, please make note of it in this bug report.
See https://fedoraproject.org/wiki/QA:Updates_Testing for
instructions on how to install test updates.
You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2017-c50bcf22f5</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10296693</commentid>
    <comment_count>3</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-04-01 13:05:34 -0400</bug_when>
    <thetext>libselinux-2.6-3.fc26 has been pushed to the Fedora 26 stable repository. If problems still persist, please make note of it in this bug report.</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>