<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.redhat.com/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.12068.1"
          urlbase="https://bugzilla.redhat.com/"
          
          maintainer="bugzilla-error-list@redhat.com"
>

    <bug>
          <bug_id>1426257</bug_id>
          
          <creation_ts>2017-02-23 09:33:00 -0500</creation_ts>
          <short_desc>windows executables in package</short_desc>
          <delta_ts>2017-04-28 10:35:35 -0400</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>2</classification_id>
          <classification>Fedora</classification>
          <product>Fedora</product>
          <component>python3</component>
          <version>26</version>
          <rep_platform>Unspecified</rep_platform>
          <op_sys>Unspecified</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>ERRATA</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords></keywords>
          <priority>unspecified</priority>
          <bug_severity>unspecified</bug_severity>
          <target_milestone>---</target_milestone>
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Matthias Runge">mrunge</reporter>
          <assigned_to name="Charalampos Stratakis">cstratak</assigned_to>
          <cc>bkabrda</cc>
    
    
    <cc>cstratak</cc>
    
    
    <cc>ishcherb</cc>
    
    
    <cc>mcyprian</cc>
    
    
    <cc>mhroncok</cc>
    
    
    <cc>pviktori</cc>
    
    
    <cc>rkuska</cc>
    
    
    <cc>tomspur</cc>
    
    
    <cc>torsava</cc>
          <qa_contact name="Fedora Extras Quality Assurance">extras-qa</qa_contact>
          
          <cf_fixed_in>python3-3.6.1-4.fc26</cf_fixed_in>
          <cf_doc_type>If docs needed, set a value</cf_doc_type>
          <cf_release_notes></cf_release_notes>
          <cf_story_points>---</cf_story_points>
          
          <cf_environment></cf_environment>
          <cf_last_closed>2017-04-28 10:35:35</cf_last_closed>
          <cf_type>Bug</cf_type>
          <cf_regression_status>---</cf_regression_status>
          <cf_mount_type>---</cf_mount_type>
          <cf_documentation_action>---</cf_documentation_action>
          <cf_crm></cf_crm>
          <cf_verified_branch></cf_verified_branch>
          <cf_category>---</cf_category>
          <cf_ovirt_team>---</cf_ovirt_team>
          
          <cf_cloudforms_team>---</cf_cloudforms_team>
          
          
          
          
          <target_release>---</target_release>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>10178510</commentid>
    <comment_count>0</comment_count>
    <who name="Matthias Runge">mrunge</who>
    <bug_when>2017-02-23 09:33:02 -0500</bug_when>
    <thetext>Description of problem:
rpm -qf /usr/lib64/python3.5/distutils/command/wininst-10.0.exe

(plus a few more in that path)

system-python-libs-3.5.3-1.fc25.x86_64


Please remove those files</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10178805</commentid>
    <comment_count>1</comment_count>
    <who name="Miro Hrončok">mhroncok</who>
    <bug_when>2017-02-23 10:37:32 -0500</bug_when>
    <thetext>I suppose we shall move those files to python3-devel to be consistent with python2 package. See bz525469 for more information.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10193416</commentid>
    <comment_count>2</comment_count>
    <who name="Fedora End Of Life">jkurik</who>
    <bug_when>2017-02-28 07:25:21 -0500</bug_when>
    <thetext>This bug appears to have been reported against &apos;rawhide&apos; during the Fedora 26 development cycle.
Changing version to &apos;26&apos;.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10346634</commentid>
    <comment_count>3</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-04-19 12:41:09 -0400</bug_when>
    <thetext>python3-3.6.1-4.fc26 has been submitted as an update to Fedora 26. https://bodhi.fedoraproject.org/updates/FEDORA-2017-e1e5e717c6</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10346671</commentid>
    <comment_count>4</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-04-19 12:53:00 -0400</bug_when>
    <thetext>python3-3.6.1-4.fc26 python3-docs-3.6.1-1.fc26 has been submitted as an update to Fedora 26. https://bodhi.fedoraproject.org/updates/FEDORA-2017-e1e5e717c6</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10347953</commentid>
    <comment_count>5</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-04-19 22:22:41 -0400</bug_when>
    <thetext>python3-3.6.1-4.fc26, python3-docs-3.6.1-1.fc26 has been pushed to the Fedora 26 testing repository. If problems still persist, please make note of it in this bug report.
See https://fedoraproject.org/wiki/QA:Updates_Testing for
instructions on how to install test updates.
You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2017-e1e5e717c6</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10372530</commentid>
    <comment_count>6</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-04-28 10:35:35 -0400</bug_when>
    <thetext>python3-3.6.1-4.fc26, python3-docs-3.6.1-1.fc26 has been pushed to the Fedora 26 stable repository. If problems still persist, please make note of it in this bug report.</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>